/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package signify;

import Algo.ISignify;
import Algo.Signify_LSB_Basic;
import Algo.Signify_LSB_Modrate;
import Algo.Signify_LSB_Advance;
import java.awt.Color;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author jay
 */
public class MainActivity extends javax.swing.JFrame {

    /**
     * Creates new form MainActivity
     */
    public MainActivity() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        browesImgBtn = new javax.swing.JButton();
        ImgPath = new javax.swing.JLabel();
        maxDataLabel = new javax.swing.JLabel();
        hideDataBtn = new javax.swing.JButton();
        warningLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jRadioButtonBasic = new javax.swing.JRadioButton();
        jRadioButtonModrate = new javax.swing.JRadioButton();
        jRadioButtonAdvanced = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jOptionPane3 = new javax.swing.JOptionPane();
        jPanel2 = new javax.swing.JPanel();
        browesImgBtn1 = new javax.swing.JButton();
        warningMsg1 = new javax.swing.JLabel();
        retrieveDataBtn = new javax.swing.JButton();
        dataRetreivePath = new javax.swing.JLabel();
        jOptionPane1 = new javax.swing.JOptionPane();
        jRadioButtonBasic1 = new javax.swing.JRadioButton();
        jRadioButtonModrate1 = new javax.swing.JRadioButton();
        jRadioButtonAdvanced1 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        browesImgBtn.setText("Browes Image");
        browesImgBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browesImgBtnActionPerformed(evt);
            }
        });

        ImgPath.setText("Image Path : ");

        maxDataLabel.setText("Max Storable Data : ");

        hideDataBtn.setText("Hide Data");
        hideDataBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hideDataBtnActionPerformed(evt);
            }
        });

        warningLabel.setForeground(new java.awt.Color(234, 33, 33));
        warningLabel.setText(" ");

        jButton1.setText("Browse File");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("File Path :");

        buttonGroup1.add(jRadioButtonBasic);
        jRadioButtonBasic.setText("Basic [More Data, Low Security]");

        buttonGroup1.add(jRadioButtonModrate);
        jRadioButtonModrate.setText("Modrate [More Data, Modrate Security]");

        buttonGroup1.add(jRadioButtonAdvanced);
        jRadioButtonAdvanced.setText("Advanced [Less Data, High Security]");

        jLabel3.setText("Signification Preference");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(maxDataLabel)
                            .addComponent(hideDataBtn)
                            .addComponent(warningLabel)
                            .addComponent(ImgPath))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonBasic)
                            .addComponent(jRadioButtonModrate)
                            .addComponent(jRadioButtonAdvanced)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jOptionPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(browesImgBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(159, 159, 159))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(browesImgBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonBasic)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButtonModrate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButtonAdvanced)
                        .addGap(44, 44, 44))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addGap(60, 60, 60)
                        .addComponent(jOptionPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(ImgPath)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(maxDataLabel)
                .addGap(18, 18, 18)
                .addComponent(hideDataBtn)
                .addGap(18, 18, 18)
                .addComponent(warningLabel)
                .addGap(22, 22, 22))
        );

        jTabbedPane1.addTab("Hide Data", jPanel1);

        browesImgBtn1.setText("Browes Image");
        browesImgBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browesImgBtn1ActionPerformed(evt);
            }
        });

        warningMsg1.setForeground(new java.awt.Color(194, 16, 16));
        warningMsg1.setText(" ");

        retrieveDataBtn.setText("Retrieve Data");
        retrieveDataBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retrieveDataBtnActionPerformed(evt);
            }
        });

        buttonGroup2.add(jRadioButtonBasic1);
        jRadioButtonBasic1.setText("Basic");

        buttonGroup2.add(jRadioButtonModrate1);
        jRadioButtonModrate1.setText("Modrate");

        buttonGroup2.add(jRadioButtonAdvanced1);
        jRadioButtonAdvanced1.setText("Advanced");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(206, Short.MAX_VALUE)
                .addComponent(jOptionPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(131, 131, 131))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(browesImgBtn1)
                    .addComponent(retrieveDataBtn)
                    .addComponent(dataRetreivePath)
                    .addComponent(warningMsg1)
                    .addComponent(jRadioButtonBasic1)
                    .addComponent(jRadioButtonModrate1)
                    .addComponent(jRadioButtonAdvanced1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(browesImgBtn1)
                .addGap(4, 4, 4)
                .addComponent(dataRetreivePath)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(retrieveDataBtn)
                .addGap(65, 65, 65)
                .addComponent(jOptionPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jRadioButtonBasic1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonModrate1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonAdvanced1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                .addComponent(warningMsg1)
                .addGap(27, 27, 27))
        );

        jTabbedPane1.addTab("Retrive Data", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 607, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void browesImgBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browesImgBtnActionPerformed
        
        this.warningLabel.setText(" ");
        ISignify signify=new Signify_LSB_Basic();
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Image Files", "jpg", "png", "gif", "jpeg");
        fileChooser.setFileFilter(filter);
            int returnValue = fileChooser.showOpenDialog(null);
            if (returnValue == JFileChooser.APPROVE_OPTION) 
            {
                File selectedFile = fileChooser.getSelectedFile();
                String path= selectedFile.getPath();
                this.ImgPath.setText(path);
                try {
                    BufferedImage imgFile = ImageIO.read(new File(path));
                    System.out.println((long)signify.getMaxStorableData(imgFile));
                    String msg="Max Storable Data : "+ String.valueOf((long)signify.getMaxStorableData(imgFile)/(8.0*1024))+"kB" ;//bits/8=bytes
                    this.maxDataLabel.setText(msg);
                } catch (IOException ex) {
                    Logger.getLogger(MainActivity.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

    }//GEN-LAST:event_browesImgBtnActionPerformed

    private void hideDataBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hideDataBtnActionPerformed
        
        BufferedImage imgFile;
        try {
            imgFile = ImageIO.read(new File(this.ImgPath.getText()));
            
            ISignify signify=null;
            String sign="";
            
            if(jRadioButtonBasic.isSelected())
            {
                signify=new Signify_LSB_Basic();
            }
            else if(jRadioButtonModrate.isSelected())
            {
                sign = jOptionPane3.showInputDialog("Enter your Secret Key(Seven Digit Alphanumeric)");
                if(sign.length()!=7)
                {
                    this.warningLabel.setText("Enter exactly seven digit alpha numeric");
                    return;
                }
                signify=new Signify_LSB_Modrate();
            }
            else if(jRadioButtonAdvanced.isSelected())
            {
                signify=new Signify_LSB_Advance();
            }
            else
            {
                this.warningLabel.setForeground(Color.red);
                this.warningLabel.setText("Please Select Signification Preference");
                return;
            }
            
            if(new File(this.jLabel2.getText()).length()*8>(signify.getMaxStorableData(imgFile)))
            {
                this.warningLabel.setForeground(Color.red);
                this.warningLabel.setText("Either choose bigger File or shorten your message");
                return;
            }
            signify.hideData(this.jLabel2.getText(), this.ImgPath.getText(),sign);
            this.warningLabel.setForeground(new Color(19,185,49));
            this.warningLabel.setText("Data Hidden Successfully");
        }
        catch (IOException ex)
        {
            this.warningLabel.setForeground(Color.red);
            this.warningLabel.setText("Choose Image File First");
            Logger.getLogger(MainActivity.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_hideDataBtnActionPerformed

    private void browesImgBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browesImgBtn1ActionPerformed
        
        this.warningMsg1.setText(" ");
        
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Image Files", "jpg", "png", "gif", "jpeg");
        fileChooser.setFileFilter(filter);
            int returnValue = fileChooser.showOpenDialog(null);
            if (returnValue == JFileChooser.APPROVE_OPTION) 
            {
                File selectedFile = fileChooser.getSelectedFile();
                String path= selectedFile.getPath();
                this.dataRetreivePath.setText(path);
            }
    }//GEN-LAST:event_browesImgBtn1ActionPerformed

    private void retrieveDataBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retrieveDataBtnActionPerformed
       
        try {
            //String secret= Signify_LSB_Modrate.retrieveData(this.dataRetreivePath.getText());
            ISignify signify=null;
            String sign="";
            
            if(jRadioButtonBasic1.isSelected())
            {
                signify=new Signify_LSB_Basic();
            }
            else if(jRadioButtonModrate1.isSelected())
            {
                sign = jOptionPane1.showInputDialog("Enter your Secret Key");
                signify=new Signify_LSB_Modrate();
            }
            else if(jRadioButtonAdvanced1.isSelected())
            {
                signify=new Signify_LSB_Advance();
            }
            else
            {
                this.warningMsg1.setForeground(Color.red);
                this.warningMsg1.setText("Please Select Level of Security");
                return;
            }
            
            String status=signify.retrieveData(this.dataRetreivePath.getText(),sign);
            this.warningMsg1.setForeground(new Color(19,185,49));
            this.warningMsg1.setText(status);
        
        } 
        catch (IOException ex)
        {
            this.warningMsg1.setForeground(Color.red);
            this.warningMsg1.setText("Choose Image File First");
            Logger.getLogger(MainActivity.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_retrieveDataBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        //FileNameExtensionFilter filter = new FileNameExtensionFilter("Image Files", "jpg", "png", "gif", "jpeg");
        //fileChooser.setFileFilter(filter);
            int returnValue = fileChooser.showOpenDialog(null);
            if (returnValue == JFileChooser.APPROVE_OPTION) 
            {
                File selectedFile = fileChooser.getSelectedFile();
                String path= selectedFile.getPath();
                this.jLabel2.setText(path);
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainActivity().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ImgPath;
    private javax.swing.JButton browesImgBtn;
    private javax.swing.JButton browesImgBtn1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel dataRetreivePath;
    private javax.swing.JButton hideDataBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JOptionPane jOptionPane3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButtonAdvanced;
    private javax.swing.JRadioButton jRadioButtonAdvanced1;
    private javax.swing.JRadioButton jRadioButtonBasic;
    private javax.swing.JRadioButton jRadioButtonBasic1;
    private javax.swing.JRadioButton jRadioButtonModrate;
    private javax.swing.JRadioButton jRadioButtonModrate1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel maxDataLabel;
    private javax.swing.JButton retrieveDataBtn;
    private javax.swing.JLabel warningLabel;
    private javax.swing.JLabel warningMsg1;
    // End of variables declaration//GEN-END:variables
}
